[[language]]
name = "python"
auto-format = true
language-servers = ["pyrefly", "ruff"]
roots = ["pyproject.toml"]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.ruff]
command = "ruff"
args = ["server"]


